server:
  port: 8080


spring:
  flyway:
    baseline-on-migrate: true
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/logistic
    username: postgres
    password: ricardo12
